=== yuaner999/sc/xmldesign/schemas/crudapp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 (http://www.altova.com) by  () -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="app">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="crud">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="formsql"/>
							<xs:element name="tableheadersql"/>
						</xs:sequence>
						<xs:attribute name="title" use="required"/>
						<xs:attribute name="tabletitle" use="required"/>
						<xs:attribute name="tabledataurl" use="required"/>
						<xs:attribute name="formcreatesubmiturl" use="required"/>
						<xs:attribute name="formeditsubmiturl" use="required"/>
						<xs:attribute name="saveto" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== yuaner999/sc/xmldesign/app/crudapp/admin.xml
<app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/crudapp.xsd">
    <crud title="商店人员管理"
          saveto="admin/shopusermanagement.jsp"
          tabletitle="人员列表"
          tabledataurl="jsons/shopallusers.form"
          formcreatesubmiturl="jsons/shopcreateuser.form"
          formeditsubmiturl="jsons/shopedituser.form">
        <formsql>select * from sysuser</formsql>
        <tableheadersql>select * from shop_group_user_view</tableheadersql>
    </crud>
    <crud title="组管理" tabletitle="组列表"
          tabledataurl="jsons/shopallgroups.form"
          formcreatesubmiturl="jsons/shopaddgroup.form"
          formeditsubmiturl="shopeditgroup"
          saveto="admin/shopgroupmanagement.jsp">
        <formsql>select * from sysgroup</formsql>
        <tableheadersql>select * from shop_group_view</tableheadersql>
    </crud>
    <crud title="权限管理" tabletitle="权限列表" tabledataurl="jsons/shopallprivilege.form"
          formcreatesubmiturl="shopaddprivilege"
          formeditsubmiturl="shopeditprivilege"
          saveto="admin/privilegemanagement.jsp">
        <formsql>select * from sysprivilege</formsql>
        <tableheadersql>select * from sysprivilege</tableheadersql>
    </crud>
</app>
