=== yuaner999/sc/xmldesign/schemas/easyui.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 (http://www.altova.com) by liuzg (neu) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="app">
		<xs:complexType>
			<xs:choice>
				<xs:group ref="allcontrols"/>
				<xs:element ref="javascript"/>
				<xs:element name="test">
					<xs:complexType>
						<xs:attribute name="id" use="required"/>
						<xs:attribute name="name"/>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:attribute name="title" use="optional" default="网页标题"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="button">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="jscmds" minOccurs="0"/>
				<xs:group ref="jslogic"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="toolbarline">
		<xs:complexType>
			<xs:group ref="basiccontrols" minOccurs="0" maxOccurs="unbounded"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="toolbar">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="toolbarline" minOccurs="0" maxOccurs="unbounded"/>
				<xs:group ref="basiccontrols" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="datagrid">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="toolbar" minOccurs="0"/>
				<xs:element name="headers">
					<xs:complexType>
						<xs:attribute name="sql" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required"/>
			<xs:attribute name="title" type="xs:string" use="required"/>
			<xs:attribute name="url" type="xs:string" use="required"/>
			<xs:attribute name="height" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="dialog">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="buttons" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="button" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="content" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:group ref="allcontrols" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element ref="toolbar" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required"/>
			<xs:attribute name="title" type="xs:string" use="required"/>
			<xs:attribute name="width" type="xs:string"/>
			<xs:attribute name="height" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="combobox">
		<xs:complexType>
			<xs:attribute name="id" type="xs:ID" use="required"/>
			<xs:attribute name="url" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="label">
		<xs:complexType>
			<xs:attribute name="id" type="xs:ID"/>
			<xs:attribute name="text" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="panel">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="toolbarline"/>
				<xs:element name="content">
					<xs:complexType>
						<xs:group ref="allcontrols"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required"/>
			<xs:attribute name="title" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:group name="basiccontrols">
		<xs:sequence>
			<xs:element ref="button" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="combobox" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="label" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="allcontrols">
		<xs:sequence>
			<xs:group ref="basiccontrols" minOccurs="0" maxOccurs="unbounded"/>
			<xs:group ref="containers" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="containers">
		<xs:sequence>
			<xs:element ref="datagrid" minOccurs="0"/>
			<xs:element ref="panel" minOccurs="0"/>
			<xs:element ref="dialog" minOccurs="0"/>
			<xs:element ref="form" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:element name="form">
		<xs:complexType>
			<xs:attribute name="id" type="xs:ID"/>
			<xs:attribute name="method" type="xs:string" default="post"/>
			<xs:attribute name="url" type="xs:string"/>
			<xs:attribute name="fieldsql" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="javascript">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="startup" minOccurs="0">
					<xs:complexType>
						<xs:group ref="jscmds"/>
					</xs:complexType>
				</xs:element>
				<xs:element ref="function" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:group name="jscmds">
		<xs:sequence>
			<xs:element ref="formload" minOccurs="0"/>
			<xs:element ref="formreset" minOccurs="0"/>
			<xs:element ref="formsubmit" minOccurs="0"/>
			<xs:element ref="dialogclose" minOccurs="0"/>
			<xs:element ref="dialogopen" minOccurs="0"/>
			<xs:element ref="dialogtitle" minOccurs="0"/>
			<xs:element ref="alert" minOccurs="0"/>
			<xs:element ref="datagridreload" minOccurs="0"/>
			<xs:element ref="datagridselected" minOccurs="0"/>
			<xs:element ref="panelopen" minOccurs="0"/>
			<xs:element ref="panelclose" minOccurs="0"/>
			<xs:element ref="messagerfade" minOccurs="0"/>
			<xs:element ref="messagerprogressclose" minOccurs="0"/>
			<xs:element ref="messagerprogressopen" minOccurs="0"/>
			<xs:element ref="messagershow" minOccurs="0"/>
			<xs:element ref="messagerslide" minOccurs="0"/>
			<xs:element ref="formloaddata" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:element name="formload">
		<xs:complexType>
			<xs:attribute name="formid" use="required"/>
			<xs:attribute name="url" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="formreset">
		<xs:complexType>
			<xs:attribute name="formid" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="formsubmit">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="jscmds"/>
			</xs:sequence>
			<xs:attribute name="formid" use="required"/>
			<xs:attribute name="url" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="function">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="jscmds"/>
				<xs:group ref="jslogic"/>
			</xs:sequence>
			<xs:attribute name="name" use="required"/>
			<xs:attribute name="parameters"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="dialogclose">
		<xs:complexType>
			<xs:attribute name="dialogid"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="dialogopen">
		<xs:complexType>
			<xs:attribute name="dialogid"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="alert">
		<xs:complexType>
			<xs:attribute name="text" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="datagridreload">
		<xs:complexType>
			<xs:attribute name="datagridid" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="datagridselected">
		<xs:complexType>
			<xs:attribute name="datagridid" use="required"/>
			<xs:attribute name="var" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="panelopen">
		<xs:complexType>
			<xs:attribute name="panelid" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="panelclose">
		<xs:complexType>
			<xs:attribute name="panelid" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="messagerfade">
		<xs:complexType>
			<xs:attribute name="title" use="required"/>
			<xs:attribute name="msg" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="messagerprogressclose"/>
	<xs:element name="messagerprogressopen">
		<xs:complexType>
			<xs:attribute name="title" use="required"/>
			<xs:attribute name="msg" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="messagershow">
		<xs:complexType>
			<xs:attribute name="title" use="required"/>
			<xs:attribute name="msg" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="messagerslide">
		<xs:complexType>
			<xs:attribute name="title" use="required"/>
			<xs:attribute name="msg" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="dialogtitle">
		<xs:complexType>
			<xs:attribute name="dialogid" use="required"/>
			<xs:attribute name="title" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:group name="jslogic">
		<xs:sequence>
			<xs:element ref="if"/>
			<xs:element ref="else"/>
			<xs:element ref="elseif"/>
		</xs:sequence>
	</xs:group>
	<xs:element name="if">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="jscmds"/>
				<xs:group ref="jslogic"/>
			</xs:sequence>
			<xs:attribute name="condition" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="else">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="jscmds"/>
				<xs:group ref="jslogic"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="elseif">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="jscmds"/>
				<xs:group ref="jslogic"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="formloaddata">
		<xs:complexType>
			<xs:attribute name="formid" use="required"/>
			<xs:attribute name="var" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== yuaner999/sc/xmldesign/app/easyui/shopproduct.xml
<app title="商品管理" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/easyui.xsd">
    <combobox id="test" url="a.form"/>
    <datagrid id="dg" title="商品列表" url="jsons/shopproducts.form">
        <headers sql="select * from product"/>
        <toolbar>
            <toolbarline>
                <button id="btnadd">
                    <dialogopen dialogid="dlgcreate"/>
                </button>
                <button id="btnedit">
                    <datagridselected datagridid="dg" var="data"/>
                    <if condition="data">
                        <dialogopen dialogid="dlgedit"/>
                        <formloaddata formid="frmedit" var="data"/>
                    </if>
                    <else>
                        <alert text="请选择要操作的数据"/>
                    </else>
                </button>
                <button id="btndelete">
                    <datagridselected datagridid="dg" var="data"/>
                    <if condition="data">
                        <alert text="ajax code:delete"/>
                    </if>
                    <else>
                        <alert text="请选择要操作的数据"/>
                    </else>
                </button>
            </toolbarline>
        </toolbar>
    </datagrid>

    <dialog id="dlgcreate" title="添加商品">
        <buttons>
            <button id="dlgcreateok">
                <formsubmit formid="frmcreate" url="jsons/shopaddproduct.form" >
                    <alert text="数据已提交"/>
                    <dialogclose dialogid="dlgcreate" />
                    <datagridreload datagridid="dg"/>
                </formsubmit>
            </button>
            <button id="dlgcreatecancel">
                <dialogclose dialogid="dlgcreate"/>
            </button>
        </buttons>
        <content>
            <form id="frmcreate" method="post" fieldsql="select * from product" />
        </content>
    </dialog>

    <dialog id="dlgedit" title="添加商品">
        <buttons>
            <button id="dlgeditok">
                <formsubmit formid="frmedit" url="jsons/shopeditproduct.form" >
                    <alert text="数据已提交"/>
                    <dialogclose dialogid="dlgedit" />
                    <datagridreload datagridid="dg"/>
                </formsubmit>
            </button>
            <button id="dlgeditcancel">
                <dialogclose dialogid="dlgedit"/>
            </button>
        </buttons>
        <content>
            <form id="frmedit" method="post" fieldsql="select * from product" />
        </content>

    </dialog>

    <javascript>
        <startup>
            <dialogclose dialogid="dlgcreate"/>
            <dialogclose dialogid="dlgedit"/>
        </startup>
    </javascript>

</app>

=== yuaner999/sc/xmldesign/app/easyui/user.xml
<app title="用户管理" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/easyui.xsd">
    <datagrid id="dg" title="人员列表" url="jsons/allusers.form">
        <headers sql="select * from sysuser"/>
        <toolbar>
            <toolbarline>
                <button id="btnadd">
                    <dialogopen dialogid="dlgcreate"/>
                </button>
                <button id="btnedit">
                    <datagridselected datagridid="dg" var="data"/>
                    <if condition="data">
                        <formloaddata formid="frmedit" var="data"/>
                        <dialogopen dialogid="dlgedit"/>
                    </if>
                    <else>
                        <alert text="选择要操作的数据"/>
                    </else>
                </button>
                <button id="btndelete"></button>
            </toolbarline>
        </toolbar>
    </datagrid>

    <dialog id="dlgcreate" title="创建用户" >
        <buttons>
            <button id="dlgcreateok">
                <formsubmit formid="frmcreate" url="jsons/createuser.form">
                    <alert text="已创建成功"/>
                    <dialogclose dialogid="dlgcreate"/>
                    <datagridreload datagridid="dg"/>
                </formsubmit>
            </button>
            <button id="dlgcreatecancel">
                <dialogclose dialogid="dlgcreate"/>
            </button>
        </buttons>
        <content>
            <form id="frmcreate" method="post" fieldsql="select * from sysuser"/>
        </content>
    </dialog>

    <dialog id="dlgedit" title="编辑用户" >
        <buttons>
            <button id="dlgeditok">
                <formsubmit formid="frmedit" url="jsons/edituser.form">
                    <alert text="已保存成功"/>
                    <dialogclose dialogid="dlgedit"/>
                    <datagridreload datagridid="dg"/>
                </formsubmit>
            </button>
            <button id="dlgeditcancel">
                <dialogclose dialogid="dlgedit"/>
            </button>
        </buttons>
        <content>
            <form id="frmedit" method="post" fieldsql="select * from sysuser"/>
        </content>
    </dialog>


    <javascript>
        <startup>
            <dialogclose dialogid="dlgcreate"/>
            <dialogclose dialogid="dlgedit"/>

        </startup>
    </javascript>
    
</app>
