=== yuaner999/sc/xmldesign/schemas/websm.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 (http://www.altova.com) by  () -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="beans">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="statemachine" minOccurs="0"/>
				<xs:element ref="json" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="statemachine">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="state" minOccurs="0"/>
				<xs:element ref="transition" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="state">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="processorgroup"/>
			</xs:sequence>
			<xs:attribute name="name" use="required"/>
			<xs:attribute name="viewname"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="transition">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="processors" minOccurs="0">
					<xs:complexType>
						<xs:group ref="processorgroup"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="condition" minOccurs="0">
					<xs:complexType>
						<xs:group ref="conditiongroup"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="from" use="required"/>
			<xs:attribute name="to" use="required"/>
			<xs:attribute name="on"/>
		</xs:complexType>
	</xs:element>
	<xs:group name="processorgroup">
		<xs:sequence>
			<xs:element ref="sqlquery" minOccurs="0"/>
			<xs:element ref="excelopenxml" minOccurs="0"/>
			<xs:element ref="excel97" minOccurs="0"/>
			<xs:element ref="wordopenxml" minOccurs="0"/>
			<xs:element ref="word97" minOccurs="0"/>
			<xs:element ref="foreach" minOccurs="0"/>
			<xs:element ref="if" minOccurs="0"/>
			<xs:element ref="ref" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="conditiongroup">
		<xs:sequence>
			<xs:element ref="sqlcondition" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:element name="sqlcondition"/>
	<xs:element name="output">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="field" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="jxpath"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="sqlquery">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="sql"/>
				<xs:element name="objmap" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="propertymappingsetting" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="key" use="required"/>
			<xs:attribute name="datatype" use="required"/>
			<xs:attribute name="totalrowsvar"/>
			<xs:attribute name="resultvar"/>
			<xs:attribute name="resultmsgvar"/>
			<xs:attribute name="pagevar"/>
			<xs:attribute name="pagesizevar"/>
			<xs:attribute name="id"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="propertymappingsetting">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="propertymappingsetting"/>
			</xs:sequence>
			<xs:attribute name="field"/>
			<xs:attribute name="property"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ref">
		<xs:complexType>
			<xs:attribute name="beanid" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="json">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sqlquery"/>
				<xs:element ref="output"/>
				<xs:element ref="ref"/>
			</xs:sequence>
			<xs:attribute name="id"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="field">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="field" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="key" use="required"/>
			<xs:attribute name="jxpath"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="excelopenxml">
		<xs:complexType>
			<xs:attribute name="id"/>
			<xs:attribute name="templatefile" use="required"/>
			<xs:attribute name="outfile" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="excel97">
		<xs:complexType>
			<xs:attribute name="id"/>
			<xs:attribute name="templatefile" use="required"/>
			<xs:attribute name="outfile" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="wordopenxml">
		<xs:complexType>
			<xs:attribute name="id"/>
			<xs:attribute name="templatefile" use="required"/>
			<xs:attribute name="outfile" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="foreach">
		<xs:complexType>
			<xs:attribute name="var" use="required"/>
			<xs:attribute name="items" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="word97">
		<xs:complexType>
			<xs:attribute name="id"/>
			<xs:attribute name="templatefile" use="required"/>
			<xs:attribute name="outfile" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="if">
		<xs:complexType>
			<xs:attribute name="jxpathcondition"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== yuaner999/sc/xmldesign/springxml/json.xml
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/websm.xsd">

    <!--*****************************系统后台管理*****************************-->
    <!--=============================系统用户管理=============================-->
    <!--*****************************以下内容禁止修改、删除，直到结尾END*****************************START-->
    <!--加载系统用户-->
    <json id="delete_review">
        <sqlquery key="data" datatype="void" resultvar="r" resultmsgvar="rmsg">
            <sql>delete from supplement where id=${id}</sql>
        </sqlquery>
        <output>
            <field key="resultSet" jxpath="./data"/>
            <field key="result" jxpath="./r"/>
            <field key="errormessage" jxpath="./rmsg"/>
        </output>
    </json>

    <json id="loadSysUser">
        <sqlquery key="data" datatype="list" totalrowsvar="total" pagevar="page" pagesizevar="rows">
            <sql><![CDATA[
           SELECT sysuser.*,sysrole.`sysrole_name`, FROM_UNIXTIME(UNIX_TIMESTAMP(sysuser.create_date),'%Y-%m-%d %H:%i:%s') AS create_date,
            FROM_UNIXTIME(UNIX_TIMESTAMP(sysuser.update_date),'%Y-%m-%d %H:%i:%s') AS update_date
            FROM sysuser LEFT JOIN sysrole ON(sysuser.`sysrole_id`=sysrole.`sysrole_id`)
             WHERE is_sysadmin='否' AND ((${sqlStr} IS NULL) OR (username LIKE CONCAT('%',${sqlStr},'%'))) ORDER BY create_date DESC
            ]]></sql>
        </sqlquery>
        <output>
            <field key="rows" jxpath="data"/>
            <field key="total" jxpath="total"/>
        </output>
    </json>
    <!--修改用户-->
    <json id="editSysUser">
        <sqlquery key="data" datatype="void" resultvar="r" resultmsgvar="rmsg">
            <sql><![CDATA[
                update sysuser
                set sysrole_id=${sysroleid},update_date=now(),update_man=${loginName},remark=${remark}
                where sysuser_id=${sysuserid}
                ]]></sql>
        </sqlquery>
        <output>
            <field key="resultSet" jxpath="./data"/>
            <field key="result" jxpath="./r"/>
            <field key="errormessage" jxpath="./rmsg"/>
        </output>
    </json>
    <!--删除用户-->
    <json id="deleteSysUser">
        <sqlquery key="data" datatype="void" resultvar="r" resultmsgvar="rmsg">
            <sql>delete from sysuser where sysuser_id=${sysuserid}</sql>
        </sqlquery>
        <output>
            <field key="resultSet" jxpath="./data"/>
            <field key="result" jxpath="./r"/>
            <field key="errormessage" jxpath="./rmsg"/>
        </output>
    </json>
    <!--删除用户  其他部门-->
    <json id="deleteUser">
        <sqlquery key="data" datatype="void" resultvar="r" resultmsgvar="rmsg">
            <sql><![CDATA[
               call lrf_delete_user(${sysuserid},${role})
                ]]></sql>
        </sqlquery>
        <output>
            <field key="resultSet" jxpath="./data"/>
            <field key="result" jxpath="./r"/>
            <field key="errormessage" jxpath="./rmsg"/>
        </output>
    </json>
    <!--添加用户  其他部门-->
    <json id="addUser">
        <sqlquery key="data" datatype="void" resultvar="r" resultmsgvar="rmsg">
            <sql><![CDATA[
                call lrf_add_user(${username},${sysroleid},${college},${dept},${grade},${class},${type},${loginName},${remark})
                ]]></sql>
        </sqlquery>
        <output>
            <field key="resultSet" jxpath="./data"/>
            <field key="result" jxpath="./r"/>
            <field key="errormessage" jxpath="./rmsg"/>
        </output>
    </json>
    <!--修改   其他用户-->
    <json id="editUser">
        <sqlquery key="data" datatype="void" resultvar="r" resultmsgvar="rmsg">
            <sql><![CDATA[
               call lrf_update_user(${sysuserid},${username},${sysroleid},${college},${dept},${grade},${class},${type},${loginName},${remark})
                ]]></sql>
        </sqlquery>
        <output>
            <field key="resultSet" jxpath="./data"/>
            <field key="result" jxpath="./r"/>
            <field key="errormessage" jxpath="./rmsg"/>
        </output>
    </json>
    <!--查询用户角色-->
    <json id="selectsysrole_id">
        <sqlquery key="data" datatype="list" totalrowsvar="total" pagevar="page" pagesizevar="rows">
            <sql><![CDATA[
                 SELECT sysrole_id from sysuser where username=${username}
            ]]></sql>
        </sqlquery>
        <output>
            <field key="rows" jxpath="data"/>
            <field key="total" jxpath="total"/>
        </output>
    </json>
    <!--验证是否是导员-->
    <json id="selectinstructor">
        <sqlquery key="data" datatype="list" totalrowsvar="total" pagevar="page" pagesizevar="rows">
            <sql><![CDATA[
                 SELECT * from instructor where instructorLogin=${username}
            ]]></sql>
        </sqlquery>
        <output>
            <field key="rows" jxpath="data"/>
            <field key="total" jxpath="total"/>
        </output>
    </json>
    <!--=============================系统菜单管理=============================-->
    <!--新建菜单-->
    <json id="addMenu">
        <sqlquery key="data" datatype="void" resultvar="r" resultmsgvar="rmsg">
            <sql><![CDATA[
                INSERT INTO sysmenu (sysmenu_id,sysmenu_name,sysmenu_url,parent_menuid,is_sysmanage_menu,sort,create_date,create_man,remark)
                VALUES(uuid(),${sysmenuname},${sysmenuurl},${parentmenuid},'否',${sort},now(),${loginName},${remark})
                ]]></sql>
        </sqlquery>
        <output>
            <field key="resultSet" jxpath="./data"/>
            <field key="result" jxpath="./r"/>
            <field key="errormessage" jxpath="./rmsg"/>
        </output>
    </json>
    <!--修改菜单-->
    <json id="editMenu">
        <sqlquery key="data" datatype="void" resultvar="r" resultmsgvar="rmsg">
            <sql><![CDATA[
                UPDATE sysmenu
                SET sysmenu_name=${sysmenuname},sysmenu_url=${sysmenuurl},
                    parent_menuid=${parentmenuid},sort=${sort},
                    update_date=now(),update_man=${loginName},
                    remark=${remark}
                WHERE sysmenu_id=${sysmenuid} and sysmenu_id!='2c659331-0d1a-11e6-b867-0025b6dd0800'
                ]]></sql>
        </sqlquery>
        <output>
            <field key="resultSet" jxpath="./data"/>
            <field key="result" jxpath="./r"/>
            <field key="errormessage" jxpath="./rmsg"/>
        </output>
    </json>
    <!--删除菜单-->
    <json id="deleteMenu">
        <sqlquery key="data" datatype="void" resultvar="r" resultmsgvar="rmsg">
            <sql>DELETE FROM sysmenu WHERE sysmenu_id=${sysmenuid} and is_sysmanage_menu='否'</sql>
        </sqlquery>
        <output>
            <field key="resultSet" jxpath="./data"/>
            <field key="result" jxpath="./r"/>
            <field key="errormessage" jxpath="./rmsg"/>
        </output>
    </json>
    <!--=============================系统角色管理=============================-->
    <!--加载系统角色-->
    <json id="loadSysRole">
        <sqlquery key="data" datatype="list" totalrowsvar="total" pagevar="page" pagesizevar="rows">
            <sql><![CDATA[
                select *,FROM_UNIXTIME(UNIX_TIMESTAMP(create_date),'%Y-%m-%d %H:%i:%s') AS create_date,FROM_UNIXTIME(UNIX_TIMESTAMP(update_date),'%Y-%m-%d %H:%i:%s') AS update_date
                from sysrole where
                is_sysrole in ('是','否') and ((${sqlStr} is null) or (sysrole_name like concat('%',${sqlStr},'%')))
                order by create_date desc
                ]]></sql>
        </sqlquery>
        <output>
            <field key="rows" jxpath="data"/>
            <field key="total" jxpath="total"/>
        </output>
    </json>
    <!--新建角色-->
    <json id="addRole">
        <sqlquery key="data" datatype="void" resultvar="r" resultmsgvar="rmsg">
            <sql><![CDATA[
                INSERT INTO sysrole (sysrole_id,sysrole_name,is_sysrole,create_date,create_man,remark)
                VALUES(uuid(),${sysrolename},'否',now(),${loginName},${remark})
                ]]></sql>
        </sqlquery>
        <output>
            <field key="resultSet" jxpath="./data"/>
            <field key="result" jxpath="./r"/>
            <field key="errormessage" jxpath="./rmsg"/>
        </output>
    </json>
    <!--修改角色-->
    <json id="editRole">
        <sqlquery key="data" datatype="void" resultvar="r" resultmsgvar="rmsg">
            <sql><![CDATA[
                UPDATE sysrole SET
                  sysrole_name=${sysrolename},update_date=now(),update_man=${loginName},remark=${remark}
                  WHERE sysrole_id=${sysroleid} ;
                ]]></sql>
        </sqlquery>
        <output>
            <field key="resultSet" jxpath="./data"/>
            <field key="result" jxpath="./r"/>
            <field key="errormessage" jxpath="./rmsg"/>
        </output>
    </json>
    <!--删除角色-->
    <json id="deleteRole">
        <sqlquery key="data" datatype="void" resultvar="r" resultmsgvar="rmsg">
            <sql>DELETE FROM sysrole WHERE sysrole_id=${sysroleid} and sysrole_id!='fe785f38-0baf-11e6-883e-0025b6dd0800'</sql>
        </sqlquery>
        <output>
            <field key="resultSet" jxpath="./data"/>
            <field key="result" jxpath="./r"/>
            <field key="errormessage" jxpath="./rmsg"/>
        </output>
    </json>
    <!--角色权限，加载角色名称-->
    <json id="getRoleName">
        <sqlquery key="data" datatype="list" totalrowsvar="total" >
            <sql>SELECT * FROM sysrole where is_sysrole!='2654264'</sql>
        </sqlquery>
        <output>
            <field key="rows" jxpath="./data"/>
            <field key="total" jxpath="./total"/>
        </output>
    </json>
    <!--角色权限，获取选中角色的权限菜单-->
    <json id="getRoleMenu">
        <sqlquery key="data" datatype="list" resultvar="r" resultmsgvar="rmsg">
            <sql>SELECT * FROM sysrolemenu where sysrole_id=${sysroleId}</sql>
        </sqlquery>
        <output>
